name: feature-pipeline  # Define the name of the GitHub Actions workflow

on:  # Specify the triggers for the workflow
  schedule:  # Define a schedule trigger
    - cron: '0 * * * *'  # Run the workflow every hour at the start of the hour

  workflow_dispatch:  # Allow the workflow to be manually triggered from the GitHub UI

jobs:
  feature_pipeline:
    runs-on: windows-latest  # Specify the OS to run the job on (latest Windows)

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Installing Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Installing Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # Verify Poetry installation
      - name: Verify Poetry installation
        run: poetry --version

      # Poetry install to install all the dependencies or requirements
      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      # Run the feature pipeline notebook from the command line (using run jupyter nbconvert)
      - name: Execute Python workflow from batch script
        env:  
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: poetry run jupyter nbconvert --to notebook --execute notebooks/12_feature_pipeline.ipynb
